name: quant-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyarrow
  - pandas
  - sqlalchemy
  - psycopg
  - selenium
  - python-dotenv
  - prefect
  - requests
  - streamlit
  - pip
  - pip:
    - kiteconnect
    - watchdog
    - zope.interface
    - pyotp
    - lxml
    - anthropic 
    - arelle-release
    - bs4
    - google-cloud-aiplatform
    - google-auth
    - PyPDF2
    - pyyaml